"use client";
import React, { useState, useEffect } from "react";
import { supabase, isConfigured } from "@/lib/supabaseClient";
import { Link2, ExternalLink, RefreshCw, Globe, Calendar, User } from "lucide-react";

type CommentReply = {
  id: string;
  comment_id: string;
  post_id: string;
  group_url: string;
  comment_url?: string;
  account_name?: string;
  replied_at: string;
};

export default function URLGallery() {
  const [replies, setReplies] = useState<CommentReply[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchCommentURLs();
  }, []);

  const fetchCommentURLs = async () => {
    setLoading(true);
    if (!isConfigured) {
      setLoading(false);
      return;
    }

    try {
      const { data, error } = await supabase
        .from("replies_log")
        .select("*")
        // Legacy DRY_RUN rows are not real comments — hide them.
        .not("comment_id", "like", "dryrun_%")
        .not("comment_id", "like", "unverified_%")
        .not("comment_id", "like", "comment_%")
        .order("replied_at", { ascending: false });

      if (error) throw error;
      if (data) {
        setReplies(data as CommentReply[]);
      }
    } catch (e) {
      console.error("Error fetching comment URLs:", e);
    } finally {
      setLoading(false);
    }
  };

  const getCleanGroupName = (url: string) => {
    return url
      .replace(/https?:\/\/www\.facebook\.com\/groups\//, "")
      .replace(/\/$/, "");
  };

  const getAccountBadge = (accountName?: string, commentId?: string) => {
    const isBooster = commentId?.startsWith("booster_") || accountName?.toLowerCase().includes("booster");
    if (isBooster) return "Account 3 (Booster)";
    if (accountName?.toLowerCase().includes("reports")) return "Account 2 (Taylor)";
    return "Account 1 (Ilse)";
  };

  return (
    <div className="p-6 md:p-8 space-y-8 max-w-7xl mx-auto font-sans animate-in fade-in duration-500">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <h1 className="text-2xl font-black text-slate-900 tracking-tight">
              URL Gallery 🔗
            </h1>
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-indigo-50 text-indigo-700 border border-indigo-200">
              <Link2 className="w-3.5 h-3.5" /> Comment Links
            </span>
          </div>
          <p className="text-xs font-medium text-slate-500">
            A live catalog of all target post comments generated by the VPS bot (real-time links).
          </p>
        </div>

        <button
          onClick={fetchCommentURLs}
          className="flex items-center gap-2 px-4 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-bold transition-all"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          Refresh URLs
        </button>
      </div>

      {/* URL Grid List */}
      {loading ? (
        <div className="p-12 text-center text-slate-400 bg-white rounded-3xl border border-slate-200 font-medium">
          Loading comment logs from Supabase...
        </div>
      ) : replies.length === 0 ? (
        <div className="p-12 text-center bg-white rounded-3xl border border-slate-200 shadow-sm">
          <Link2 className="w-12 h-12 text-slate-300 mx-auto mb-3" />
          <h3 className="text-sm font-bold text-slate-700">No Comment Links Found</h3>
          <p className="text-xs text-slate-400 max-w-sm mx-auto mt-1">
            The bot hasn't written any reply logs yet. New URLs will sync here automatically upon patrol comments.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {replies.map((reply) => {
            const groupName = getCleanGroupName(reply.group_url);
            const accountText = getAccountBadge(reply.account_name, reply.comment_id);
            const isBooster = accountText.includes("Booster");
            
            // Build fallback URL if comment_url is missing
            const fallbackLink = reply.group_url.startsWith("http") 
              ? reply.group_url 
              : `https://www.facebook.com/${reply.post_id}`;
            // The bot stores the real comment permalink in comment_id
            // (booster rows are prefixed `booster_`).
            const storedProof = String(reply.comment_id || "").replace(/^booster_/, "");
            const targetLink = (storedProof.startsWith("http") && storedProof)
              || reply.comment_url
              || fallbackLink;

            return (
              <div 
                key={reply.id} 
                className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm hover:shadow-md transition-all duration-300 flex flex-col justify-between space-y-4"
              >
                <div className="space-y-3">
                  {/* Badge & Time */}
                  <div className="flex items-center justify-between flex-wrap gap-2">
                    <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-lg text-[10px] font-extrabold uppercase border ${
                      isBooster 
                        ? "bg-blue-50 text-blue-700 border-blue-200" 
                        : "bg-slate-50 text-slate-700 border-slate-200"
                    }`}>
                      <User className="w-3 h-3" />
                      {accountText}
                    </span>
                    <span className="inline-flex items-center gap-1 text-[11px] text-slate-400 font-semibold">
                      <Calendar className="w-3 h-3" />
                      {new Date(reply.replied_at).toLocaleString("en-AU")}
                    </span>
                  </div>

                  {/* Target Group */}
                  <div className="space-y-1">
                    <h3 className="text-[11px] font-extrabold uppercase tracking-wider text-slate-400">Target Group</h3>
                    <a 
                      href={reply.group_url}
                      target="_blank"
                      rel="noreferrer"
                      className="text-xs font-bold text-slate-800 hover:text-indigo-600 flex items-center gap-1.5 truncate"
                    >
                      <Globe className="w-4 h-4 text-slate-400 shrink-0" />
                      <span className="truncate">{groupName}</span>
                    </a>
                  </div>
                </div>

                {/* Direct Action Link */}
                <div className="pt-2">
                  <a
                    href={targetLink}
                    target="_blank"
                    rel="noreferrer"
                    className="w-full py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 shadow-md shadow-indigo-500/10 transition-all"
                  >
                    <span>Go to Comment Post</span>
                    <ExternalLink className="w-3.5 h-3.5" />
                  </a>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
