"""Classifier keyword data — ported from bot/bot.ts. Do not hand-edit; regenerate."""

SERVICE_BOND = [
    'bond clean',
    'bond cleans',
    'bond cleaning',
    'bond cleaner',
    'bond cleaners',
    'bond back clean',
    'end of lease clean',
    'end of lease cleaning',
    'end of lease cleaner',
    'end of lease',
    'eol clean',
    'exit clean',
    'exit cleaning',
    'exit cleaner',
    'vacate clean',
    'vacate cleaning',
    'move out clean',
    'move out cleaning',
    'moving out clean',
    'move in clean',
    'move in cleaning',
    'lease clean',
    'lease cleaning',
    'final clean',
    'inspection clean',
    'rental clean',
    'rental cleaning',
    'tenancy clean',
    'end of tenancy clean',
    'handover clean',
    'pre inspection clean',
]

SERVICE_CARPET = [
    'carpet clean',
    'carpet cleans',
    'carpet cleaning',
    'carpet cleaner',
    'carpet steam clean',
    'carpet shampoo',
    'steam clean',
    'steam cleaning',
    'upholstery clean',
    'upholstery cleaning',
    'lounge clean',
    'couch clean',
    'couch cleaning',
    'sofa clean',
    'sofa cleaning',
    'mattress clean',
    'mattress cleaning',
    'rug clean',
    'rug cleaning',
    'stain removal',
]

SERVICE_COMMERCIAL = [
    'office clean',
    'office cleaning',
    'office cleaner',
    'commercial clean',
    'commercial cleaning',
    'commercial cleaner',
    'strata clean',
    'strata cleaning',
    'body corporate cleaning',
    'shop clean',
    'shop cleaning',
    'cafe clean',
    'cafe cleaning',
    'restaurant clean',
    'restaurant cleaning',
    'salon clean',
    'gym clean',
    'gym cleaning',
    'warehouse clean',
    'warehouse cleaning',
    'childcare clean',
    'childcare cleaning',
    'school clean',
    'school cleaning',
    'medical centre cleaning',
    'clinic cleaning',
    'builders clean',
    'builder clean',
    'builders cleaning',
    'post construction clean',
    'construction clean',
    'renovation clean',
    'reno clean',
    'after builders clean',
    'site clean',
    'workplace cleaning',
]

SERVICE_HOME = [
    'house clean',
    'house cleans',
    'house cleaner',
    'house cleaning',
    'home clean',
    'home cleaner',
    'home cleaning',
    'domestic clean',
    'domestic cleaner',
    'domestic cleaning',
    'residential clean',
    'residential cleaner',
    'residential cleaning',
    'housekeeper',
    'housekeeping',
    'house keeper',
    'cleaning lady',
    'cleaner',
    'cleaners',
    'cleaning',
    'cleaning service',
    'cleaning services',
    'cleaning company',
    'deep clean',
    'deep cleaning',
    'spring clean',
    'spring cleaning',
    'one off clean',
    'once off clean',
    'regular clean',
    'regular cleaning',
    'weekly clean',
    'weekly cleaning',
    'fortnightly clean',
    'fortnightly cleaning',
    'monthly clean',
    'monthly cleaning',
    'ongoing clean',
    'ongoing cleaning',
    'general clean',
    'general cleaning',
    'detailed clean',
    'full clean',
    'top to bottom clean',
    'apartment clean',
    'unit clean',
    'townhouse clean',
    'airbnb clean',
    'airbnb cleaning',
    'air bnb clean',
    'air bnb cleaning',
    'airbnb changeover',
    'airbnb turnover',
    'short stay clean',
    'short stay cleaning',
    'holiday let clean',
    'holiday rental clean',
    'ndis clean',
    'ndis cleaning',
    'ndis cleaner',
    'ndis housekeeping',
    'aged care clean',
    'aged care cleaning',
    'disability cleaning',
    'hoarding clean',
    'hoarder clean',
    'deceased estate clean',
    'squalor clean',
]

REQUEST_SIGNALS = [
    'looking for',
    'look for',
    'looking to find',
    'in search of',
    'iso',
    'need',
    'needing',
    'needed',
    'i need',
    'we need',
    'in need of',
    'want',
    'wanting',
    'wanted',
    'i want',
    'we want',
    'would like',
    'after a',
    'after an',
    'after some',
    'chasing',
    'keen for',
    'keen to find',
    'seeking',
    'searching for',
    'search for',
    'require',
    'requiring',
    'required',
    'recommend',
    'recommendation',
    'recommendations',
    'recommendations for',
    'suggestions',
    'suggestion',
    'any suggestions',
    'anyone know',
    'does anyone know',
    'anyone recommend',
    'can anyone recommend',
    'does anyone have',
    'anyone got',
    'anyone available',
    'who can',
    'who does',
    'know anyone',
    'know of anyone',
    'know someone',
    'help with',
    'need help',
    'looking for help',
    'assistance with',
    'hire',
    'hiring someone',
    'book',
    'booking',
    'book in',
    'quote',
    'quotes',
    'a quote',
    'how much',
    'price for',
    'cost of',
    'availability',
    'available this',
    'available next',
    'asap',
    'can someone',
    'someone to',
    'anyone to',
    'point me',
    'who is good',
    "who's good",
    'whos good',
    'who do you use',
    'who do you recommend',
    'who should i call',
    'who should i use',
    'anyone use',
    'anyone used',
    'used anyone',
    'any good',
    'best place for',
    'worth using',
    'thoughts on',
    'is there anyone',
    'is anyone',
    'are there any',
    'any decent',
    'any reliable',
]

STRONG_LEAD_PHRASES = [
    'looking for a cleaner',
    'looking for cleaner',
    'looking for a house cleaner',
    'looking for a domestic cleaner',
    'looking for a bond cleaner',
    'looking for a carpet cleaner',
    'looking for a window cleaner',
    'looking for a cleaning service',
    'looking for a cleaning company',
    'looking for someone to clean',
    'looking for someone who cleans',
    'looking for a reliable cleaner',
    'looking for a good cleaner',
    'looking for a regular cleaner',
    'need a cleaner',
    'need cleaner',
    'need a house cleaner',
    'need a bond cleaner',
    'need a carpet cleaner',
    'need a window cleaner',
    'need someone to clean',
    'need a cleaning service',
    'need cleaning done',
    'in need of a cleaner',
    'in need of cleaning',
    'cleaner needed',
    'cleaner wanted',
    'cleaning needed',
    'cleaning wanted',
    'cleaner required',
    'cleaning required',
    'want a cleaner',
    'wanting a cleaner',
    'after a cleaner',
    'chasing a cleaner',
    'seeking a cleaner',
    'seeking cleaner',
    'iso a cleaner',
    'iso cleaner',
    'recommend a cleaner',
    'recommend a good cleaner',
    'recommend a cleaning service',
    'recommendations for a cleaner',
    'recommendation for a cleaner',
    'anyone recommend a cleaner',
    'can anyone recommend a cleaner',
    'anyone know a cleaner',
    'anyone know a good cleaner',
    'anyone know of a cleaner',
    'does anyone know a cleaner',
    'know a good cleaner',
    'know any good cleaners',
    'any good cleaners',
    'anyone got a cleaner',
    'does anyone have a cleaner',
    'who does cleaning',
    'who can clean',
    'anyone who cleans',
    'hire a cleaner',
    'hiring a cleaner',
    'book a cleaner',
    'booking a cleaner',
    'get my house cleaned',
    'get the house cleaned',
    'want my house cleaned',
    'have my house cleaned',
    'house needs a clean',
    'house needs cleaning',
    'place needs a clean',
    'quote for cleaning',
    'quote for a clean',
    'cleaning quote',
    'how much to clean',
    'how much for a clean',
    'help with cleaning',
    'help with the cleaning',
    'help cleaning my house',
]

HARD_DISQUALIFIERS = [
    'i offer',
    'we offer',
    'i provide',
    'we provide',
    'i specialise',
    'we specialise',
    'i specialize',
    'we specialize',
    'my business',
    'our business',
    'my cleaning business',
    'our cleaning business',
    'my company',
    'our company',
    'family run business',
    'family owned business',
    'locally owned and operated',
    'book now',
    'book today',
    'book in now',
    'bookings open',
    'now taking bookings',
    'taking on new clients',
    'accepting new clients',
    'new clients welcome',
    'i have availability',
    'we have availability',
    'vacancies available',
    'sale on now',
    'services offered',
    'services include',
    'what we offer',
    'what we do',
    'services i offer',
    'our services',
    'my services',
    'price list',
    'follow my page',
    'like my page',
    'like our page',
    'check out my page',
    'check out our website',
    'visit our website',
    'link in bio',
    'testimonial',
    'testimonials',
    'looking for work',
    'looking for cleaning work',
    'seeking work',
    'seeking cleaning work',
    'available for work',
    'i am a cleaner',
    'im a cleaner',
    'i am a professional cleaner',
    'experienced cleaner available',
    'cleaner available',
    'cleaners available',
    'i clean houses',
    'i do cleaning',
    'we do cleaning',
    'happy to clean',
    'cleaning work',
    'construction cleaning work',
    'commercial cleaning work',
    'hiring cleaners',
    'we are hiring',
    'now hiring',
    'join our team',
    'cleaner position',
    'cleaning position',
    'job opening',
    'job vacancy',
    'position available',
    'positions available',
    'casual work',
    'subcontractor',
    'sub contractor',
    'subcontract',
    'resume',
    'cv',
    'work wanted',
    'seeking employment',
    'car wash',
    'car clean',
    'car detailing',
    'mobile detailing',
    'auto detailing',
    'pool clean',
    'pool cleaning',
    'pool service',
    'gutter clean',
    'gutter cleaning',
    'roof clean',
    'roof cleaning',
    'lawn',
    'lawn mowing',
    'mowing',
    'gardening',
    'garden maintenance',
    'landscaping',
    'tree lopping',
    'rubbish removal',
    'junk removal',
    'skip bin',
    'plumber',
    'plumbing',
    'electrician',
    'handyman',
    'painter',
    'painting quote',
    'removalist',
    'removalists',
    'pest control',
    'pest inspection',
    'locksmith',
    'dry cleaning',
    'dry cleaner',
    'laundromat',
    'for sale',
    'selling',
    'sell my',
    'brand new in box',
    'pick up only',
    'vacuum for sale',
    'vacuum cleaner for sale',
    'steam mop',
    'robot vacuum',
    'cleaning products',
    'cleaning supplies',
    'norwex',
    'enjo',
    'best product to clean',
    'what product',
    'which product',
    'how do i clean',
    'how do you clean',
    'how to clean',
    'any tips to clean',
    'tips for cleaning',
    'hack to clean',
    'cleaning hack',
    'cleaning hacks',
    'clean out my closet',
    'cleaning out my closet',
    'clean out my wardrobe',
    'cleaning out the shed',
    'clean eating',
    'clean energy',
    'clean water',
    'teeth clean',
    'dental clean',
    'ear clean',
    'clean driving record',
    'clean skin',
    'come clean',
    'squeaky clean bill',
    'join her team',
    'join my team',
    'join the team',
    'cleaner contractors',
    'cleaning contractors',
    'abn required',
    'start asap for',
    'send your resume',
    'apply now',
    'applications open',
    'looking for cleaners to join',
    'looking for experienced cleaners',
    'wanting to join',
    'work with us',
    'employment opportunity',
    'personal care',
    'disability support',
    'carer',
    'care worker',
    'babysitting',
    'baby sitting',
    'babysitter',
    'nanny',
    'au pair',
    'tutor',
    'dog walking',
    'pet sitting',
    'house sitting',
    'room to rent',
    'room for rent',
    'rooms for rent',
    'looking for a room',
    'looking for a rental',
    'long term rental',
    'rental application',
    'house to rent',
    'for rent',
    'tenants',
    'tenant',
    'rental property available',
    'price reduction',
    'offers over',
    'open home',
    'inspection times',
    'just listed',
    'under contract',
    'auction',
    'for lease',
    'cleaning out your',
    'clean out your',
    'cleaning out the garage',
    'cleaning out my',
    'clean out my',
    'having a clear out',
    'garage sale',
    'book your',
    'get booked',
    'giveaway',
    'bond back',
    'bond back guarantee',
    'let us',
    'we bring',
    'our professional',
    'deserve more than',
    'for your business',
    'grow your business',
    'eco friendly and vegan',
    'transformation',
    'before and after',
    'swipe to see',
    'tag someone',
    'clean hotel',
    'xero',
    'crm',
    'software',
    'platform',
    'dashboard',
    'invoices',
    'invoicing',
    'your bookings',
    'client books',
    'vendors',
    'restock',
    'keeps your whole',
    'admin',
    'subscription',
    'leads for your',
    'more clients',
    'win more',
    'scale your',
    'i recommend',
    'we recommend',
    'shout out to',
    'big thanks to',
    'thanks to',
    'thank you to',
    'just used',
    'did a great job',
    'amazing job',
    'so happy with',
]

SOFT_DISQUALIFIERS = [
    'i highly recommend',
    'can highly recommend',
    'highly recommend',
    'my team',
    'our team',
    'spots available',
    'spaces available',
    'availability this week',
    'availability next week',
    'openings available',
    'pm for a quote',
    'pm for quote',
    'dm for a quote',
    'dm for quote',
    'pm me for',
    'dm me for',
    'message me for',
    'inbox me for',
    'pm me',
    'dm me',
    'inbox me',
    'contact us',
    'call us',
    'call me on',
    'text me on',
    'give us a call',
    'get in touch',
    'reach out to us',
    'free quote',
    'free quotes',
    'no obligation quote',
    'competitive rates',
    'competitive pricing',
    'affordable rates',
    'reasonable rates',
    'best rates',
    'special offer',
    'discount',
    'promo',
    'promotion',
    'fully insured',
    'police checked',
    'abn',
    'public liability',
    'satisfaction guaranteed',
    'happiness guarantee',
    'reviews welcome',
    'own car',
    'own transport',
    'own abn',
    'good pay',
    'great pay',
    'hourly rate',
    'per hour',
    'paid weekly',
    'immediate start',
    'must have experience',
    'experience preferred',
]

OUT_OF_SCOPE = [
    'window clean',
    'window cleaning',
    'window cleaner',
    'windows cleaned',
    'window washing',
    'gutter clean',
    'gutter cleaning',
    'roof clean',
    'roof cleaning',
    'pressure clean',
    'pressure cleaning',
    'pressure wash',
    'pressure washing',
    'high pressure clean',
    'driveway clean',
    'driveway cleaning',
    'solar panel clean',
    'solar panel cleaning',
    'oven clean',
    'oven cleaning',
    'oven cleaner',
    'bbq clean',
    'bbq cleaning',
    'blind clean',
    'blind cleaning',
    'blinds cleaned',
    'curtain clean',
    'curtain cleaning',
    'curtains cleaned',
    'tile and grout',
    'grout clean',
    'grout cleaning',
    'pool clean',
    'pool cleaning',
    'car clean',
    'car detailing',
    'ironing service',
    'laundry service',
]

OWN_AD_MARKERS = [
    'fiesta fresh',
    'fiestafresh',
    'fiestafreshcleaning',
    '200% happiness guarantee',
    '200 % happiness guarantee',
    'happiness guarantee',
    'only cleaning company on the gold coast offering this',
]

GEO_EXCLUDE = [
    'adelaide',
    'melbourne',
    'sydney',
    'perth',
    'hobart',
    'darwin',
    'canberra',
    'geelong',
    'ballarat',
    'bendigo',
    'newcastle',
    'wollongong',
    'launceston',
    'townsville',
    'cairns',
    'mackay',
    'rockhampton',
    'toowoomba',
    'bundaberg',
    'brisbane',
    'logan',
    'ipswich',
    'sunshine coast',
    'victoria',
    'new south wales',
    'nsw',
    'south australia',
    'western australia',
    'tasmania',
    'northern territory',
    'mambourin',
    'new zealand',
    'auckland',
]

